//This file is related to the typeorm and database related things
import { Column, Entity, PrimaryGeneratedColumn } from 'typeorm';
import { TaskStatus } from './task-status.enum';

@Entity()
export class Task {
  // the properties in this class translates into columns in the database
  @PrimaryGeneratedColumn('uuid') //this tells typeorm that it is the primary columns(kinda primary key) and autogenerated as well.
  id: string;

  @Column()
  title: string;

  @Column()
  description: string;

  @Column()
  status: TaskStatus;
}
